<?php

namespace Database\Seeders;

use App\Models\Opd;
use Illuminate\Database\Seeder;

class OpdSeeder extends Seeder
{
    public function run(): void
    {
        $opds = [
            ['nama' => 'BADAN KEPEGAWAIAN DAN PENGEMBANGAN SUMBER DAYA MANUSIA KOTA SAMARINDA', 'singkatan' => 'BKPPD'],
            ['nama' => 'BADAN KESATUAN BANGSA DAN POLITIK', 'singkatan' => 'KESBANGPOL'],
            ['nama' => 'BADAN KESATUAN BANGSA DAN POLITIK KOTA SAMARINDA', 'singkatan' => null],
            ['nama' => 'BADAN PENANGGULANGAN BENCANA DAERAH', 'singkatan' => 'BBPBD'],
            ['nama' => 'BADAN PENDAPATAN DAERAH', 'singkatan' => 'BAPENDA'],
            ['nama' => 'BADAN PENELITIAN DAN PENGEMBANGAN', 'singkatan' => 'LITBANG'],
            ['nama' => 'BADAN PENGELOLAAN KEUANGAN DAN ASET DAERAH', 'singkatan' => null],
            ['nama' => 'BADAN PERENCANAAN PEMBANGUNAN, RISET DAN INOVASI DAERAH', 'singkatan' => 'BAPPEDA'],
            ['nama' => 'DEWAN PERWAKILAN RAKYAT DAERAH', 'singkatan' => 'DPRD'],
            ['nama' => 'DINAS KEARSIPAN', 'singkatan' => 'ARSIP'],
            ['nama' => 'DINAS KEBUDAYAAN', 'singkatan' => 'DISBUD'],
            ['nama' => 'DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL', 'singkatan' => 'DISDUKCAPIL'],
            ['nama' => 'DINAS KESEHATAN', 'singkatan' => 'DINKES'],
            ['nama' => 'DINAS KETAHANAN PANGAN', 'singkatan' => 'DKP'],
            ['nama' => 'DINAS KETAHANAN PANGAN DAN PERTANIAN', 'singkatan' => 'PERTANIAN'],
            ['nama' => 'DINAS KOMUNIKASI DAN INFORMATIKA', 'singkatan' => 'DISKOMINFO'],
            ['nama' => 'DINAS KOPERASI, USAHA KECIL MENENGAH DAN PERINDUSTRIAN', 'singkatan' => 'KOPUKM'],
            ['nama' => 'DINAS LINGKUNGAN HIDUP', 'singkatan' => 'DLH'],
            ['nama' => 'DINAS PARIWISATA', 'singkatan' => 'DISPAR'],
            ['nama' => 'DINAS PEKERJAAN UMUM DAN PENATAAN RUANG', 'singkatan' => 'PUPR'],
            ['nama' => 'DINAS PEMADAM KEBAKARAN DAN PENYELAMATAN KOTA SAMARINDA', 'singkatan' => 'DAMKAR'],
            ['nama' => 'DINAS PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK', 'singkatan' => 'DP3A'],
            ['nama' => 'DINAS PEMUDA, OLAHRAGA DAN PARIWISATA', 'singkatan' => 'DISPORA'],
            ['nama' => 'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU', 'singkatan' => 'DPMPTSP'],
            ['nama' => 'DINAS PENDIDIKAN DAN KEBUDAYAAN', 'singkatan' => 'DISDIK'],
            ['nama' => 'DINAS PENGENDALIAN PENDUDUK DAN KELUARGA BERENCANA', 'singkatan' => 'DALDUK'],
            ['nama' => 'DINAS PERDAGANGAN', 'singkatan' => 'DISDAG'],
            ['nama' => 'DINAS PERHUBUNGAN', 'singkatan' => 'DISHUB'],
            ['nama' => 'DINAS PERIKANAN', 'singkatan' => 'PERIKANAN'],
            ['nama' => 'DINAS PERINDUSTRIAN', 'singkatan' => 'DISPERIN'],
            ['nama' => 'DINAS PERPUSTAKAAN DAN KEARSIPAN', 'singkatan' => 'PERPUS'],
            ['nama' => 'DINAS PERTANAHAN', 'singkatan' => 'PERTANAHAN'],
            ['nama' => 'DINAS PERUMAHAN DAN KAWASAN PERMUKIMAN', 'singkatan' => 'PERKIM'],
            ['nama' => 'DINAS SOSIAL DAN PEMBERDAYAAN MASYARAKAT', 'singkatan' => 'DINSOS'],
            ['nama' => 'DINAS TENAGA KERJA', 'singkatan' => 'DISNAKER'],
            ['nama' => 'INSPEKTORAT DAERAH KOTA SAMARINDA', 'singkatan' => 'INSPEKTORAT'],
            ['nama' => 'KECAMATAN LOA JANAN ILIR', 'singkatan' => 'KEC-LJI'],
            ['nama' => 'KECAMATAN PALARAN', 'singkatan' => 'KEC-PALARAN'],
            ['nama' => 'KECAMATAN SAMARINDA ILIR', 'singkatan' => 'KEC-SMR-ILIR'],
            ['nama' => 'KECAMATAN SAMARINDA KOTA', 'singkatan' => 'KEC-SMR-KOTA'],
            ['nama' => 'KECAMATAN SAMARINDA SEBERANG', 'singkatan' => 'KEC-SMR-SEBERANG'],
            ['nama' => 'KECAMATAN SAMARINDA ULU', 'singkatan' => 'KEC-SMR-ULU'],
            ['nama' => 'KECAMATAN SAMARINDA UTARA', 'singkatan' => 'KEC-SMR-UTARA'],
            ['nama' => 'KECAMATAN SAMBUTAN', 'singkatan' => 'KEC-SAMBUTAN'],
            ['nama' => 'KECAMATAN SUNGAI KUNJANG', 'singkatan' => 'KEC-SEI-KUNJANG'],
            ['nama' => 'KECAMATAN SUNGAI PINANG', 'singkatan' => 'KEC-SEI-PINANG'],
            ['nama' => 'KELURAHAN AIR HITAM', 'singkatan' => null],
            ['nama' => 'KELURAHAN AIR PUTIH', 'singkatan' => null],
            ['nama' => 'KELURAHAN BANDARA', 'singkatan' => null],
            ['nama' => 'KELURAHAN BANTUAS', 'singkatan' => null],
            ['nama' => 'KELURAHAN BAQA', 'singkatan' => null],
            ['nama' => 'KELURAHAN BUDAYA PAMPANG', 'singkatan' => null],
            ['nama' => 'KELURAHAN BUGIS', 'singkatan' => null],
            ['nama' => 'KELURAHAN BUKUAN', 'singkatan' => null],
            ['nama' => 'KELURAHAN DADI MULYA', 'singkatan' => null],
            ['nama' => 'KELURAHAN GUNUNG KELUA', 'singkatan' => null],
            ['nama' => 'KELURAHAN GUNUNG LINGAI', 'singkatan' => null],
            ['nama' => 'KELURAHAN GUNUNG PANJANG', 'singkatan' => null],
            ['nama' => 'KELURAHAN HANDIL BAKTI', 'singkatan' => null],
            ['nama' => 'KELURAHAN HARAPAN BARU', 'singkatan' => null],
            ['nama' => 'KELURAHAN JAWA', 'singkatan' => null],
            ['nama' => 'KELURAHAN KARANG ANYAR', 'singkatan' => null],
            ['nama' => 'KELURAHAN KARANG ASAM ILIR', 'singkatan' => null],
            ['nama' => 'KELURAHAN KARANG ASAM ULU', 'singkatan' => null],
            ['nama' => 'KELURAHAN KARANG MUMUS', 'singkatan' => null],
            ['nama' => 'KELURAHAN LEMPAKE', 'singkatan' => null],
            ['nama' => 'KELURAHAN LOA BAKUNG', 'singkatan' => null],
            ['nama' => 'KELURAHAN LOA BUAH', 'singkatan' => null],
            ['nama' => 'KELURAHAN LOK BAHU', 'singkatan' => null],
            ['nama' => 'KELURAHAN MAKROMAN', 'singkatan' => null],
            ['nama' => 'KELURAHAN MANGKUPALAS', 'singkatan' => null],
            ['nama' => 'KELURAHAN MESJID', 'singkatan' => null],
            ['nama' => 'KELURAHAN MUGIREJO', 'singkatan' => null],
            ['nama' => 'KELURAHAN PASAR PAGI', 'singkatan' => null],
            ['nama' => 'KELURAHAN PELABUHAN', 'singkatan' => null],
            ['nama' => 'KELURAHAN PELITA', 'singkatan' => null],
            ['nama' => 'KELURAHAN PULAU ATAS', 'singkatan' => null],
            ['nama' => 'KELURAHAN RAPAK DALAM', 'singkatan' => null],
            ['nama' => 'KELURAHAN RAWA MAKMUR', 'singkatan' => null],
            ['nama' => 'KELURAHAN SAMBUTAN', 'singkatan' => null],
            ['nama' => 'KELURAHAN SELILI', 'singkatan' => null],
            ['nama' => 'KELURAHAN SEMPAJA BARAT', 'singkatan' => null],
            ['nama' => 'KELURAHAN SEMPAJA SELATAN', 'singkatan' => null],
            ['nama' => 'KELURAHAN SEMPAJA TIMUR', 'singkatan' => null],
            ['nama' => 'KELURAHAN SEMPAJA UTARA', 'singkatan' => null],
            ['nama' => 'KELURAHAN SENGKOTEK', 'singkatan' => null],
            ['nama' => 'KELURAHAN SIDODADI', 'singkatan' => null],
            ['nama' => 'KELURAHAN SIDODAMAI', 'singkatan' => null],
            ['nama' => 'KELURAHAN SIDOMULYO', 'singkatan' => null],
            ['nama' => 'KELURAHAN SIMPANG PASIR', 'singkatan' => null],
            ['nama' => 'KELURAHAN SIMPANG TIGA', 'singkatan' => null],
            ['nama' => 'KELURAHAN SINDANG SARI', 'singkatan' => null],
            ['nama' => 'KELURAHAN SUNGAI KAPIH', 'singkatan' => null],
            ['nama' => 'KELURAHAN SUNGAI KELEDANG', 'singkatan' => null],
            ['nama' => 'KELURAHAN SUNGAI PINANG DALAM', 'singkatan' => null],
            ['nama' => 'KELURAHAN SUNGAI PINANG LUAR', 'singkatan' => null],
            ['nama' => 'KELURAHAN SUNGAI SIRING', 'singkatan' => null],
            ['nama' => 'KELURAHAN TANAH MERAH', 'singkatan' => null],
            ['nama' => 'KELURAHAN TANI AMAN', 'singkatan' => null],
            ['nama' => 'KELURAHAN TELUK LERONG ILIR', 'singkatan' => null],
            ['nama' => 'KELURAHAN TELUK LERONG ULU', 'singkatan' => null],
            ['nama' => 'KELURAHAN TEMINDUNG PERMAI', 'singkatan' => null],
            ['nama' => 'KELURAHAN TENUN SAMARINDA', 'singkatan' => null],
            ['nama' => 'KEMENTERIAN AGAMA KOTA SAMARINDA', 'singkatan' => null],
            ['nama' => 'Kelurahan Bukit Pinang', 'singkatan' => null],
            ['nama' => 'Kelurahan Sungai Dama', 'singkatan' => null],
            ['nama' => 'PEMBERDAYAAN DAN KESEJAHTERAAN KELUARGA', 'singkatan' => null],
            ['nama' => 'PUSKESMAS BENGKURING', 'singkatan' => null],
            ['nama' => 'PUSKESMAS HARAPAN BARU', 'singkatan' => null],
            ['nama' => 'Pimpinan Utama', 'singkatan' => null],
            ['nama' => 'RSUD I.A MOEIS', 'singkatan' => null],
            ['nama' => 'RSUD IA MOEIS', 'singkatan' => 'RSUD'],
            ['nama' => 'SATUAN POLISI PAMONG PRAJA', 'singkatan' => null],
            ['nama' => 'SEKRETARIAT DAERAH KOTA SAMARINDA', 'singkatan' => null],
            ['nama' => 'SEKRETARIAT DPRD', 'singkatan' => 'SEKWAN'],
            ['nama' => 'TIM PENGGERAK PEMBERDAYAAN DAN KESEJAHTERAAN KELUARGA', 'singkatan' => null],
            ['nama' => 'TIM WALI KOTA UNTUK AKSELERASI PEMBANGUNAN', 'singkatan' => null],
            ['nama' => 'UPT Ps. Segiri', 'singkatan' => null],
            ['nama' => 'UPTD Laboratorium Kesehatan Daerah', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS AIR PUTIH', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS BANTUAS', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS BUKUAN', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS JUANDA', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS KAMPUNG BAQA', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS KARANG ASAM', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS LEMPAKE', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS LOA BAKUNG', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS LOK BAHU', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS MAKROMAN', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS MANGKUPALAS', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS PALARAN', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS PASUNDAN', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS REMAJA', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS SAMARINDA KOTA', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS SAMBUTAN', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS SEGIRI', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS SEMPAJA', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS SIDOMULYO', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS SUNGAI KAPIH', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS SUNGAI SIRING', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS TEMINDUNG', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS TRAUMA CENTER', 'singkatan' => null],
            ['nama' => 'UPTD PUSKESMAS WONOREJO', 'singkatan' => null],
            ['nama' => 'UPTD. Instalasi Farmasi Kota Samarinda', 'singkatan' => null],
            ['nama' => 'WALI KOTA SAMARINDA', 'singkatan' => 'WALIKOTA'],
        ];

        foreach ($opds as $opd) {
            Opd::firstOrCreate(['nama' => $opd['nama']], $opd);
        }
    }
}
